### ISSUE TITLE
error npm run with mqtt app

### ISSUE THREAD

**Issue by aymeri07** [motion-software/MqttTutorial#5]
Hi everybody,

I'm trying to get the mqtt program to work with react native. I downloaded the folder, unzipped the folder I got into it with a terminal and installed it with the command "npm install". but when I do the command "npm run ios" or "npm run android", an error appears :

``````error spawnSync xcrun ENOENT. Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MqttTutorial@0.0.1 ios: `react-native run-ios --simulator='iPhone SE'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MqttTutorial@0.0.1 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.``````

here's my log file :

``````0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ios'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'preios', 'ios', 'postios' ]
5 info lifecycle MqttTutorial@0.0.1~preios: MqttTutorial@0.0.1
6 info lifecycle MqttTutorial@0.0.1~ios: MqttTutorial@0.0.1
7 verbose lifecycle MqttTutorial@0.0.1~ios: unsafe-perm in lifecycle true
8 verbose lifecycle MqttTutorial@0.0.1~ios: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\abaldelli\Downloads\MqttTutorial-master\MqttTutorial-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\LLVM\bin;D:\Program Files\Git\cmd;C:\Program Files\OpenVPN\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files (x86)\GNU Tools ARM Embedded\6 2017-q2-update\bin;C:\Users\abaldelli\AppData\Local\Microsoft\WindowsApps;C:\Users\abaldelli\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\abaldelli\AppData\Local\Microsoft\WindowsApps;C:\Users\abaldelli\AppData\Roaming\npm;C:\Users\abaldelli\AppData\Local\Yarn\bin
9 verbose lifecycle MqttTutorial@0.0.1~ios: CWD: C:\Users\abaldelli\Downloads\MqttTutorial-master\MqttTutorial-master
10 silly lifecycle MqttTutorial@0.0.1~ios: Args: [ '/d /s /c', "react-native run-ios --simulator='iPhone SE'" ]
11 silly lifecycle MqttTutorial@0.0.1~ios: Returned: code: 1  signal: null
12 info lifecycle MqttTutorial@0.0.1~ios: Failed to exec ios script
13 verbose stack Error: MqttTutorial@0.0.1 ios: `react-native run-ios --simulator='iPhone SE'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid MqttTutorial@0.0.1
15 verbose cwd C:\Users\abaldelli\Downloads\MqttTutorial-master\MqttTutorial-master
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ios"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error MqttTutorial@0.0.1 ios: `react-native run-ios --simulator='iPhone SE'`
22 error Exit status 1
23 error Failed at the MqttTutorial@0.0.1 ios script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
``````
Do you have any idea how wrong ?

thank you in advance for your feedback.

**Comment by aymeri07** [comment]
ok i don't have simulator install
